"""Eerste versie van het datamodel

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 18:20:34.232305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dagopmerking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('tekst', sa.String(length=120), nullable=False),
    sa.Column('handmatig', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datum')
    )
    op.create_table('dienstcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nummer', sa.Integer(), nullable=False),
    sa.Column('omschrijving', sa.String(length=60), nullable=False),
    sa.Column('std_begin', sa.String(length=5), nullable=True),
    sa.Column('std_eind', sa.String(length=5), nullable=True),
    sa.Column('std_uren', sa.Float(), nullable=True),
    sa.Column('kleur_achtergrond', sa.String(length=7), nullable=False),
    sa.Column('kleur_tekst', sa.String(length=7), nullable=False),
    sa.Column('vet', sa.Boolean(), nullable=False),
    sa.Column('cursief', sa.Boolean(), nullable=False),
    sa.Column('in_agenda', sa.Boolean(), nullable=False),
    sa.Column('hele_dag_zonder_tijden', sa.Boolean(), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nummer')
    )
    op.create_table('feestdag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jaar', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('naam', sa.String(length=80), nullable=False),
    sa.Column('sleutel', sa.String(length=40), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feestdag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feestdag_jaar'), ['jaar'], unique=False)

    op.create_table('instelling',
    sa.Column('sleutel', sa.String(length=64), nullable=False),
    sa.Column('waarde', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('sleutel')
    )
    op.create_table('logboek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tijdstempel', sa.DateTime(), nullable=False),
    sa.Column('gebruiker', sa.String(length=64), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('actie', sa.String(length=60), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('week', sa.String(length=12), nullable=False),
    sa.Column('medewerker', sa.String(length=120), nullable=False),
    sa.Column('dag', sa.String(length=10), nullable=False),
    sa.Column('veld', sa.String(length=40), nullable=False),
    sa.Column('oude_waarde', sa.Text(), nullable=False),
    sa.Column('nieuwe_waarde', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logboek', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logboek_actie'), ['actie'], unique=False)
        batch_op.create_index(batch_op.f('ix_logboek_tijdstempel'), ['tijdstempel'], unique=False)

    op.create_table('login_poging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gebruikersnaam', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('tijdstip', sa.DateTime(), nullable=False),
    sa.Column('gelukt', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_poging', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_poging_gebruikersnaam'), ['gebruikersnaam'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_poging_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_poging_tijdstip'), ['tijdstip'], unique=False)

    op.create_table('medewerker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=120), nullable=False),
    sa.Column('initialen', sa.String(length=10), nullable=False),
    sa.Column('functie_opmerking', sa.String(length=120), nullable=False),
    sa.Column('volgorde', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('gearchiveerd_vanaf', sa.Date(), nullable=True),
    sa.Column('agenda_modus', sa.String(length=1), nullable=False),
    sa.Column('agenda_id', sa.String(length=255), nullable=False),
    sa.Column('agenda_laatst_gesync', sa.DateTime(), nullable=True),
    sa.Column('agenda_laatste_fout', sa.Text(), nullable=False),
    sa.Column('ics_token', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('initialen')
    )
    with op.batch_alter_table('medewerker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medewerker_ics_token'), ['ics_token'], unique=False)

    op.create_table('opmerking_kleurregel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tekst', sa.String(length=60), nullable=False),
    sa.Column('kleur_achtergrond', sa.String(length=7), nullable=False),
    sa.Column('kleur_achtergrond2', sa.String(length=7), nullable=True),
    sa.Column('kleur_tekst', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tekst')
    )
    op.create_table('vakantie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=80), nullable=False),
    sa.Column('datum_van', sa.Date(), nullable=False),
    sa.Column('datum_tot', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracturen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medewerker_id', sa.Integer(), nullable=False),
    sa.Column('jaar', sa.Integer(), nullable=False),
    sa.Column('uren', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['medewerker_id'], ['medewerker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medewerker_id', 'jaar')
    )
    op.create_table('dienst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('medewerker_id', sa.Integer(), nullable=False),
    sa.Column('dienstcode_id', sa.Integer(), nullable=True),
    sa.Column('dienstnaam_override', sa.String(length=60), nullable=False),
    sa.Column('begin', sa.String(length=5), nullable=True),
    sa.Column('eind', sa.String(length=5), nullable=True),
    sa.Column('tijden_handmatig', sa.Boolean(), nullable=False),
    sa.Column('uren_berekend', sa.Float(), nullable=True),
    sa.Column('opmerking_tekst', sa.String(length=120), nullable=False),
    sa.Column('opmerking_begin', sa.String(length=5), nullable=True),
    sa.Column('opmerking_eind', sa.String(length=5), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=False),
    sa.Column('versie', sa.Integer(), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dienstcode_id'], ['dienstcode.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medewerker_id'], ['medewerker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medewerker_id', 'datum')
    )
    with op.batch_alter_table('dienst', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dienst_datum'), ['datum'], unique=False)
        batch_op.create_index(batch_op.f('ix_dienst_dienstcode_id'), ['dienstcode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dienst_medewerker_id'), ['medewerker_id'], unique=False)

    op.create_table('gebruiker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gebruikersnaam', sa.String(length=64), nullable=False),
    sa.Column('weergavenaam', sa.String(length=120), nullable=False),
    sa.Column('wachtwoord_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('medewerker_id', sa.Integer(), nullable=True),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('moet_wachtwoord_wijzigen', sa.Boolean(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.Column('laatst_ingelogd', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medewerker_id'], ['medewerker.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gebruikersnaam')
    )
    op.create_table('sync_wachtrij',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medewerker_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('soort', sa.String(length=20), nullable=False),
    sa.Column('niet_voor', sa.DateTime(), nullable=False),
    sa.Column('pogingen', sa.Integer(), nullable=False),
    sa.Column('laatste_fout', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.Column('extra', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['medewerker_id'], ['medewerker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_wachtrij', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_wachtrij_niet_voor'), ['niet_voor'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_wachtrij_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_wachtrij', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_wachtrij_status'))
        batch_op.drop_index(batch_op.f('ix_sync_wachtrij_niet_voor'))

    op.drop_table('sync_wachtrij')
    op.drop_table('gebruiker')
    with op.batch_alter_table('dienst', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dienst_medewerker_id'))
        batch_op.drop_index(batch_op.f('ix_dienst_dienstcode_id'))
        batch_op.drop_index(batch_op.f('ix_dienst_datum'))

    op.drop_table('dienst')
    op.drop_table('contracturen')
    op.drop_table('vakantie')
    op.drop_table('opmerking_kleurregel')
    with op.batch_alter_table('medewerker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medewerker_ics_token'))

    op.drop_table('medewerker')
    with op.batch_alter_table('login_poging', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_poging_tijdstip'))
        batch_op.drop_index(batch_op.f('ix_login_poging_ip'))
        batch_op.drop_index(batch_op.f('ix_login_poging_gebruikersnaam'))

    op.drop_table('login_poging')
    with op.batch_alter_table('logboek', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logboek_tijdstempel'))
        batch_op.drop_index(batch_op.f('ix_logboek_actie'))

    op.drop_table('logboek')
    op.drop_table('instelling')
    with op.batch_alter_table('feestdag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feestdag_jaar'))

    op.drop_table('feestdag')
    op.drop_table('dienstcode')
    op.drop_table('dagopmerking')
    # ### end Alembic commands ###
